[package]
name = "managed-liquidity-vault"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
stellar-access = "0.7.2"
stellar-contract-utils = "0.7.2"
stellar-macros = "0.7.2"
cvlr = { version = "0.4.1", default-features = false, optional = true }
cvlr-soroban = { version = "0.4.0", optional = true }
cvlr-soroban-derive = { version = "0.4.0", optional = true }

[features]
certora = ["dep:cvlr", "dep:cvlr-soroban", "dep:cvlr-soroban-derive"]

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
